# Generated by Django 5.1.7 on 2026-07-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_color_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['base_color', 'highlight'], 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='design',
            options={'ordering': ['design_code'], 'verbose_name_plural': 'Designs'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_id'], 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveConstraint(
            model_name='subcategory',
            name='unique_subcategory_per_category',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='unique_subcategory_per_category'),
        ),
    ]
