# Generated by Django 5.1.7 on 2026-07-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_design_design_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='legacy_design_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
