# Generated by Django 5.1.7 on 2026-07-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
