# Generated by Django 5.1.7 on 2026-09-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='marketplaces',
            field=models.ManyToManyField(blank=True, related_name='images', to='main.marketplace'),
        ),
    ]
