# Generated by Django 5.1.7 on 2026-07-19 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_color_options_alter_design_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_code',
            field=models.CharField(db_index=True, max_length=5),
        ),
        migrations.AddConstraint(
            model_name='design',
            constraint=models.UniqueConstraint(fields=('subcategory', 'design_code'), name='unique_design_per_subcategory'),
        ),
    ]
