# Generated by Django 5.1.7 on 2026-07-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_order_table_alter_orderitem_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
    ]
