# Generated by Django 5.1.7 on 2026-10-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='core.marketplace')),
            ],
            options={
                'verbose_name': 'Marketplace Field',
                'verbose_name_plural': 'Marketplace Fields',
                'db_table': 'marketplace_field',
                'ordering': ['marketplace', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_subcategories', to='core.marketplace')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketplace_configurations', to='core.subcategory')),
            ],
            options={
                'verbose_name': 'Marketplace Subcategory',
                'verbose_name_plural': 'Marketplace Subcategories',
                'db_table': 'marketplace_subcategory',
                'ordering': ['marketplace', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSubcategoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_order', models.PositiveIntegerField()),
                ('data_type', models.CharField(choices=[('TEXT', 'Text'), ('NUMBER', 'Number'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('URL', 'URL'), ('DATE', 'Date'), ('DATETIME', 'DateTime')], max_length=20)),
                ('cardinality', models.CharField(choices=[('SINGLE', 'Single'), ('MULTI', 'Multiple')], default='SINGLE', max_length=10)),
                ('requirement_type', models.CharField(choices=[('REQUIRED', 'Required'), ('CONDITIONAL', 'Conditionally Required'), ('OPTIONAL', 'Optional'), ('RECOMMENDED', 'Recommended'), ('SYSTEM', 'System Filled')], default='OPTIONAL', max_length=20)),
                ('usage', models.JSONField(blank=True, default=list)),
                ('example', models.TextField(blank=True)),
                ('validation_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_configurations', to='Marketplaces.marketplacefield')),
                ('marketplace_subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='Marketplaces.marketplacesubcategory')),
            ],
            options={
                'verbose_name': 'Marketplace Subcategory Field',
                'verbose_name_plural': 'Marketplace Subcategory Fields',
                'db_table': 'marketplace_subcategory_field',
                'ordering': ['marketplace_subcategory', 'column_order'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFieldRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.JSONField(default=dict)),
                ('action', models.JSONField(default=dict)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_subcategory_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='Marketplaces.marketplacesubcategoryfield')),
            ],
            options={
                'verbose_name': 'Marketplace Field Rule',
                'verbose_name_plural': 'Marketplace Field Rules',
                'db_table': 'marketplace_field_rule',
                'ordering': ['marketplace_subcategory_field', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('PRODUCT', 'Product'), ('PRODUCT_VARIANT', 'Product Variant'), ('MARKETPLACE_LISTING', 'Marketplace Listing'), ('CONSTANT', 'Constant'), ('CALCULATED', 'Calculated'), ('GENERATED', 'Generated'), ('USER_INPUT', 'User Input'), ('SYSTEM', 'System')], max_length=30)),
                ('source_field', models.CharField(blank=True, max_length=255)),
                ('transformation', models.CharField(blank=True, max_length=100)),
                ('transformation_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace_subcategory_field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mapping', to='Marketplaces.marketplacesubcategoryfield')),
            ],
            options={
                'verbose_name': 'Marketplace Field Mapping',
                'verbose_name_plural': 'Marketplace Field Mappings',
                'db_table': 'marketplace_field_mapping',
            },
        ),
        migrations.CreateModel(
            name='ValidValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('display_value', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('marketplace_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valid_values', to='Marketplaces.marketplacefield')),
            ],
            options={
                'verbose_name': 'Valid Value',
                'verbose_name_plural': 'Valid Values',
                'db_table': 'marketplace_valid_value',
                'ordering': ['marketplace_field', 'sequence', 'value'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSubcategoryFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('marketplace_subcategory_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_values', to='Marketplaces.marketplacesubcategoryfield')),
                ('valid_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategory_usages', to='Marketplaces.validvalue')),
            ],
            options={
                'verbose_name': 'Marketplace Subcategory Field Value',
                'verbose_name_plural': 'Marketplace Subcategory Field Values',
                'db_table': 'marketplace_subcategory_field_value',
                'ordering': ['marketplace_subcategory_field', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='marketplacefield',
            constraint=models.UniqueConstraint(fields=('marketplace', 'code'), name='unique_marketplace_field_code'),
        ),
        migrations.AddConstraint(
            model_name='marketplacesubcategory',
            constraint=models.UniqueConstraint(fields=('marketplace', 'subcategory'), name='unique_marketplace_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='marketplacesubcategoryfield',
            constraint=models.UniqueConstraint(fields=('marketplace_subcategory', 'marketplace_field'), name='unique_marketplace_subcategory_field'),
        ),
        migrations.AddConstraint(
            model_name='marketplacesubcategoryfield',
            constraint=models.UniqueConstraint(fields=('marketplace_subcategory', 'column_order'), name='unique_marketplace_subcategory_column_order'),
        ),
        migrations.AddConstraint(
            model_name='validvalue',
            constraint=models.UniqueConstraint(fields=('marketplace_field', 'value'), name='unique_valid_value_per_marketplace_field'),
        ),
        migrations.AddConstraint(
            model_name='marketplacesubcategoryfieldvalue',
            constraint=models.UniqueConstraint(fields=('marketplace_subcategory_field', 'valid_value'), name='unique_allowed_value_per_subcategory_field'),
        ),
    ]
