# Generated by Django 5.1.7 on 2026-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marketplacesubcategoryfield',
            name='unique_marketplace_subcategory_field',
        ),
        migrations.AddField(
            model_name='marketplacesubcategoryfield',
            name='attribute_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketplacesubcategoryfield',
            name='column_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
